from .attribute import Attribute
from .att_arrival import ArrivalDate
from .att_roomtype import RoomType
from .att_phonenumber import PhoneNumber
from .att_numdays import NumDays
from .att_namesurname import NameSurname
from .att_localizer import Localizer
from .att_dni import Dni
from .att_creditcard import CreditCard
from .att_roomkey import RoomKey
